// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zqWL3iLIaHSKe8x2njAQJ5AOCh00Rxo',
    appId: '1:845731035159:web:76c111da81633b08b00452',
    messagingSenderId: '845731035159',
    projectId: 'iasd-admin',
    authDomain: 'iasd-admin.firebaseapp.com',
    databaseURL: 'https://iasd-admin-default-rtdb.firebaseio.com',
    storageBucket: 'iasd-admin.appspot.com',
    measurementId: 'G-65QWD8ZZB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcqr-PLzFJ8gagplddBvcjlr-J5gM-l_A',
    appId: '1:845731035159:android:724fa4e8fd43f367b00452',
    messagingSenderId: '845731035159',
    projectId: 'iasd-admin',
    databaseURL: 'https://iasd-admin-default-rtdb.firebaseio.com',
    storageBucket: 'iasd-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYrXqBvTkv4qZQD1pQd90bd6RhTc16BE',
    appId: '1:845731035159:ios:9775122103450a53b00452',
    messagingSenderId: '845731035159',
    projectId: 'iasd-admin',
    databaseURL: 'https://iasd-admin-default-rtdb.firebaseio.com',
    storageBucket: 'iasd-admin.appspot.com',
    iosClientId: '845731035159-3n3svd1roqhenn9tesv7q34vvsdk3u8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.iasdMyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYrXqBvTkv4qZQD1pQd90bd6RhTc16BE',
    appId: '1:845731035159:ios:9775122103450a53b00452',
    messagingSenderId: '845731035159',
    projectId: 'iasd-admin',
    databaseURL: 'https://iasd-admin-default-rtdb.firebaseio.com',
    storageBucket: 'iasd-admin.appspot.com',
    iosClientId: '845731035159-3n3svd1roqhenn9tesv7q34vvsdk3u8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.iasdMyadmin',
  );
}
